services:
  client:
    build:
      target: prod
    volumes: []

  server:
    build:
      target: prod
    volumes: []

  traefik:
    build:
      context: ./traefik
    ports:
      - "80:80"
    command: []
    volumes: []