services:
  client:
    build:
      context: ./client
      target: devel
    depends_on:
      - server
    restart: unless-stopped
    volumes:
      - ./client:/app:z
      - /app/node_modules
    networks:
      - frontnet

  server:
    build:
      context: ./server
      target: devel
    depends_on:
      - database
    restart: unless-stopped
    volumes:
      - ./server:/app:z
      - /app/node_modules
    networks:
      - backnet
      - frontnet

  database:
    image: mongo:8.2.5
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - backnet

  traefik:
    image: traefik:3.6.12
    command:
      - "--entrypoints.web.address=:80"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
    ports:
      - "8000:80"
    volumes:
      - ./traefik/dynamic:/etc/traefik/dynamic:z
    networks:
      - frontnet
      - backnet
    depends_on:
      - client
      - server

volumes:
  mongo-data:

networks:
  backnet:
  frontnet: