services:
  client:
    build:
      target: prod
    volumes: []

  server:
    build:
      target: prod
    volumes: []

  traefik:
    command:
      - "--providers.file.watch=false"
    ports:
      - "80:80"