entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "jakebytes@gmail.com"
      storage: "/var/traefik/acme.json"
      tlsChallenge: {}

providers:
  file:
    directory: "/etc/traefik/dynamic"
